[build]
  # Verzeichnis mit Frontend-Dateien (wo memobox.html liegt)
  publish = "/"
  # Verzeichnis mit den Serverless Functions
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  [functions.node_config]
    # Empfohlene Node.js Version für Netlify Functions
    nodeVersion = "18"

    # Optional: Einfacherer API-Pfad (kannst du erstmal auskommentiert lassen oder entfernen)
# [[redirects]]
#  from = "/api/*"
#  to = "/.netlify/functions/:splat"
#  status = 200